/**
 * Midterm 1/2569 - Sales for Professional Business (v2)
 * GitHub Pages frontend + Google Apps Script API + Google Sheets
 * Randomly assigns ONE complete exam set (ชุดที่ 1-5) per student.
 */
const SPREADSHEET_ID='1ihwm5kmIFcYNOm_QvyMqsyn-fp8dYDWNCm5AM5k9ksE';
const TZ='Asia/Bangkok';
const SH={SETTINGS:'SETTINGS',STUDENTS:'STUDENTS',QUESTIONS:'QUESTIONS',SESSIONS:'SESSIONS',RESPONSES:'RESPONSES',AUDIT:'AUDIT'};

function doGet(e){try{const p=Object.assign({},(e&&e.parameter)||{});const a=String(p.action||'config');delete p.action;return json_(dispatch_(a,p,'GET'));}catch(err){return json_({ok:false,error:err.message||String(err)});}}
function doPost(e){try{const b=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');return json_(dispatch_(String(b.action||''),b.payload||{},'POST'));}catch(err){return json_({ok:false,error:err.message||String(err)});}}
function dispatch_(a,p,m){if(m==='GET'&&['config','lookupStudent','heartbeat'].indexOf(a)<0)throw new Error('Method not allowed');let d;
 switch(a){case'config':d=config_();break;case'lookupStudent':d=lookup_(p);break;case'startExam':d=lock_(()=>start_(p));break;case'saveAnswer':d=lock_(()=>save_(p));break;case'heartbeat':d=heartbeat_(p);break;case'reportEvent':d=lock_(()=>event_(p));break;case'submitExam':d=lock_(()=>submitById_(p.sessionId,p.reason||'MANUAL'));break;case'teacherLogin':d=teacherLogin_(p);break;case'teacherDashboard':d=dashboard_(p);break;case'toggleExam':d=lock_(()=>toggle_(p));break;case'resetAttempt':d=lock_(()=>reset_(p));break;default:throw new Error('Unknown action');}
 return{ok:true,data:d};}

function config_(){const s=settings_();return{title:s.EXAM_TITLE||'แบบทดสอบกลางภาคเรียนที่ 1 ปีการศึกษา 2569',course:s.COURSE||'การขายสำหรับนักธุรกิจมืออาชีพ',durationMin:num_(s.DURATION_MIN,40),questionCount:num_(s.QUESTION_COUNT,30),examOpen:bool_(s.EXAM_OPEN),showScore:bool_(s.SHOW_SCORE),maxTabSwitch:num_(s.MAX_TAB_SWITCH,3),passPercent:num_(s.PASS_PERCENT,60)};}
function lookup_(p){const s=settings_();examCode_(p.examCode,s);const st=student_(p.studentId);if(!st||!st.active||!allowedClass_(st.className,s))return{found:false};return{found:true,studentId:st.studentId,fullName:st.fullName,className:st.className,seatNo:st.seatNo,alreadyTaken:!!responseByStudent_(st.studentId)};}

function start_(p){const s=settings_();examCode_(p.examCode,s);window_(s);if(!bool_(s.EXAM_OPEN))throw new Error('ข้อสอบยังไม่เปิด กรุณารอครูผู้คุมสอบ');
 const st=student_(p.studentId);if(!st||!st.active||!allowedClass_(st.className,s))throw new Error('ไม่พบรหัสนักเรียนในรายชื่อผู้เข้าสอบ');if(bool_(s.ONE_ATTEMPT)&&responseByStudent_(st.studentId))return{alreadyTaken:true};
 const old=activeSessionByStudent_(st.studentId);if(old){if(Date.now()>=old.expiresAt.getTime())return{alreadyTaken:true,autoSubmitted:true,result:submitInternal_(old,'TIME_EXPIRED')};return sessionPayload_(old,s,true);}
 const bank=questions_().filter(q=>q.active);if(!bank.length)throw new Error('ยังไม่มีข้อสอบที่เปิดใช้งานในชีต QUESTIONS');
 const count=Math.min(num_(s.QUESTION_COUNT,30),bank.length);const groups={};bank.forEach(q=>{const g=q.group||'ไม่ระบุชุด';(groups[g]||(groups[g]=[])).push(q);});
 const eligible=Object.keys(groups).filter(g=>groups[g].length>=count);let setName='สุ่มจากคลังทั้งหมด',pool=bank;if(eligible.length){setName=eligible[Math.floor(Math.random()*eligible.length)];pool=groups[setName];}
 const picked=shuffle_(pool.slice()).slice(0,count),order=picked.map(q=>q.qid),choiceMap={};picked.forEach(q=>choiceMap[q.qid]=shuffle_([0,1,2,3]));
 const now=new Date();let exp=new Date(now.getTime()+num_(s.DURATION_MIN,40)*60000);if(s.END_TIME){const end=new Date(s.END_TIME);if(!isNaN(end.getTime())&&end<exp)exp=end;}
 const sid=Utilities.getUuid();append_(SH.SESSIONS,{SessionID:sid,StudentID:st.studentId,FullName:st.fullName,Class:st.className,StartedAt:now,ExpiresAt:exp,Status:'ACTIVE',CurrentIndex:0,QuestionOrderJSON:JSON.stringify(order),ChoiceOrderJSON:JSON.stringify(choiceMap),AnswersJSON:'{}',TabSwitchCount:0,LastSeen:now,UserAgent:String(p.userAgent||'').slice(0,500)});audit_(sid,st.studentId,'START','เริ่มสอบ '+setName);return sessionPayload_(sessionById_(sid),s,false);}

function save_(p){const ss=requireActive_(p.sessionId);if(Date.now()>=ss.expiresAt.getTime())return{finished:true,result:submitInternal_(ss,'TIME_EXPIRED')};const order=parse_(ss.questionOrderJson,[]),i=num_(ss.currentIndex,0),qid=order[i];if(!qid||String(p.qid)!==String(qid))throw new Error('ลำดับข้อสอบไม่ถูกต้อง กรุณารีเฟรชหน้า');const di=Number(p.choiceIndex);if([0,1,2,3].indexOf(di)<0)throw new Error('กรุณาเลือกคำตอบ');const cmap=parse_(ss.choiceOrderJson,{}),perm=cmap[qid]||[0,1,2,3],ans=parse_(ss.answersJson,{});ans[qid]=Number(perm[di]);const next=i+1;updateSession_(ss.row,{CurrentIndex:next,AnswersJSON:JSON.stringify(ans),LastSeen:new Date()});audit_(ss.sessionId,ss.studentId,'ANSWER','ตอบข้อ '+qid);const fresh=sessionById_(ss.sessionId);if(next>=order.length)return{finished:true,result:submitInternal_(fresh,'COMPLETED')};return{finished:false,question:questionPayload_(fresh)};}
function heartbeat_(p){const ss=sessionById_(p.sessionId);if(!ss)throw new Error('ไม่พบเซสชันสอบ');if(ss.status!=='ACTIVE')return{active:false,status:ss.status};if(Date.now()>=ss.expiresAt.getTime())return lock_(()=>{const f=sessionById_(p.sessionId);return!f||f.status!=='ACTIVE'?{active:false}:{active:false,expired:true,result:submitInternal_(f,'TIME_EXPIRED')};});updateSession_(ss.row,{LastSeen:new Date()});return{active:true,serverNowMs:Date.now(),expiresAtMs:ss.expiresAt.getTime(),tabSwitchCount:num_(ss.tabSwitchCount,0)};}
function event_(p){const ss=sessionById_(p.sessionId);if(!ss||ss.status!=='ACTIVE')return{active:false};const ev=String(p.event||'EVENT');let n=num_(ss.tabSwitchCount,0);if(ev==='APP_SWITCH'||ev==='FULLSCREEN_EXIT'){n++;updateSession_(ss.row,{TabSwitchCount:n,LastSeen:new Date()});}audit_(ss.sessionId,ss.studentId,ev,String(p.details||'').slice(0,500));const max=num_(settings_().MAX_TAB_SWITCH,3);if(n>=max){const f=sessionById_(ss.sessionId);return{active:false,forcedSubmit:true,tabSwitchCount:n,maxTabSwitch:max,result:submitInternal_(f,'TAB_SWITCH_LIMIT')};}return{active:true,tabSwitchCount:n,maxTabSwitch:max};}
function submitById_(sid,reason){const ss=sessionById_(sid);if(!ss)throw new Error('ไม่พบเซสชันสอบ');return ss.status==='ACTIVE'?submitInternal_(ss,reason):existingResult_(sid);}
function submitInternal_(ss,reason){if(!ss||ss.status!=='ACTIVE')return existingResult_(ss&&ss.sessionId);const order=parse_(ss.questionOrderJson,[]),ans=parse_(ss.answersJson,{}),map={};questions_().forEach(q=>map[q.qid]=q);let score=0,max=0;order.forEach(id=>{const q=map[id];if(!q)return;const pt=num_(q.points,1);max+=pt;const ci=['A','B','C','D'].indexOf(q.correct);if(Number(ans[id])===ci)score+=pt;});const t=new Date(),mins=Math.max(0,Math.round(((t-ss.startedAt)/60000)*10)/10),pct=max?Math.round(score/max*10000)/100:0;updateSession_(ss.row,{Status:reason==='COMPLETED'?'SUBMITTED':'AUTO_SUBMITTED',LastSeen:t});append_(SH.RESPONSES,{SubmittedAt:t,StudentID:ss.studentId,FullName:ss.fullName,Class:ss.className,Score:score,MaxScore:max,Percent:pct,DurationMin:mins,TabSwitchCount:num_(ss.tabSwitchCount,0),Reason:String(reason),AnswersJSON:JSON.stringify(ans),SessionID:ss.sessionId});audit_(ss.sessionId,ss.studentId,'SUBMIT',String(reason));const show=bool_(settings_().SHOW_SCORE);return{submitted:true,reason:reason,message:'ระบบได้รับคำตอบเรียบร้อยแล้ว',score:show?score:null,maxScore:show?max:null,percent:show?pct:null};}

function teacherLogin_(p){admin_(p.pin,settings_());return{ok:true};}
function dashboard_(p){const s=settings_();admin_(p.pin,s);const rs=objects_(sheet_(SH.RESPONSES)),ss=objects_(sheet_(SH.SESSIONS)),students=objects_(sheet_(SH.STUDENTS)).filter(r=>String(r.Active||'TRUE').toUpperCase()!=='FALSE');const rows=rs.map(r=>({submittedAt:fmt_(r.SubmittedAt),studentId:String(r.StudentID||''),fullName:String(r.FullName||''),className:String(r.Class||''),score:Number(r.Score||0),maxScore:Number(r.MaxScore||0),percent:Number(r.Percent||0),durationMin:Number(r.DurationMin||0),tabSwitchCount:Number(r.TabSwitchCount||0),reason:String(r.Reason||'')})).reverse();const avg=rows.length?Math.round(rows.reduce((a,r)=>a+r.percent,0)/rows.length*100)/100:0,pass=num_(s.PASS_PERCENT,60);return{examOpen:bool_(s.EXAM_OPEN),totalStudents:students.length,submittedCount:rows.length,activeCount:ss.filter(r=>String(r.Status)==='ACTIVE').length,averagePercent:avg,passCount:rows.filter(r=>r.percent>=pass).length,responses:rows};}
function toggle_(p){const s=settings_();admin_(p.pin,s);setSetting_('EXAM_OPEN',p.open?'TRUE':'FALSE');return{examOpen:!!p.open};}
function reset_(p){const s=settings_();admin_(p.pin,s);const id=String(p.studentId||'').trim();if(!id)throw new Error('กรุณาระบุรหัสนักเรียน');deleteByStudent_(SH.RESPONSES,id);deleteByStudent_(SH.SESSIONS,id);audit_('',id,'RESET_ATTEMPT','ครูรีเซ็ตสิทธิ์สอบ');return{reset:true,studentId:id};}

function ss_(){return SpreadsheetApp.openById(SPREADSHEET_ID);}function sheet_(n){const sh=ss_().getSheetByName(n);if(!sh)throw new Error('ไม่พบชีต '+n);return sh;}
function objects_(sh){if(sh.getLastRow()<1)return[];const v=sh.getDataRange().getValues(),d=sh.getDataRange().getDisplayValues(),h=d[0].map(String);return v.slice(1).map((r,i)=>{const o={};h.forEach((x,j)=>{if(!x)return;o[x]=['StudentID','SessionID','QID','Class','Correct','Active','Status','Reason','KEY','VALUE','Group'].indexOf(x)>=0?d[i+1][j]:r[j];});return o;});}
function settings_(){const o={};objects_(sheet_(SH.SETTINGS)).forEach(r=>o[String(r.KEY||'').trim()]=String(r.VALUE==null?'':r.VALUE).trim());return o;}
function setSetting_(k,v){const sh=sheet_(SH.SETTINGS),d=sh.getDataRange().getDisplayValues();for(let i=1;i<d.length;i++)if(String(d[i][0]).trim()===k){sh.getRange(i+1,2).setValue(v);return;}sh.appendRow([k,v,'']);}
function student_(id){id=String(id||'').trim();const r=objects_(sheet_(SH.STUDENTS)).find(x=>String(x.StudentID||'').trim()===id);return r?{studentId:String(r.StudentID||''),fullName:String(r.FullName||''),className:String(r.Class||''),seatNo:String(r.SeatNo||''),active:String(r.Active||'TRUE').toUpperCase()!=='FALSE'}:null;}
function questions_(){return objects_(sheet_(SH.QUESTIONS)).map(r=>({qid:String(r.QID||'').trim(),group:String(r.Group||'').trim(),question:String(r.Question||''),choices:[String(r.A||''),String(r.B||''),String(r.C||''),String(r.D||'')],correct:String(r.Correct||'').trim().toUpperCase(),points:num_(r.Points,1),active:String(r.Active||'TRUE').toUpperCase()!=='FALSE'})).filter(q=>q.qid&&['A','B','C','D'].indexOf(q.correct)>=0);}
function responseByStudent_(id){return objects_(sheet_(SH.RESPONSES)).find(r=>String(r.StudentID||'').trim()===String(id).trim())||null;}
function sessions_(){const sh=sheet_(SH.SESSIONS);if(sh.getLastRow()<=1)return[];const v=sh.getDataRange().getValues(),d=sh.getDataRange().getDisplayValues(),h=d[0],ix={};h.forEach((x,i)=>ix[x]=i);return v.slice(1).map((r,i)=>({row:i+2,sessionId:String(d[i+1][ix.SessionID]||''),studentId:String(d[i+1][ix.StudentID]||''),fullName:String(d[i+1][ix.FullName]||''),className:String(d[i+1][ix.Class]||''),startedAt:new Date(r[ix.StartedAt]),expiresAt:new Date(r[ix.ExpiresAt]),status:String(d[i+1][ix.Status]||''),currentIndex:Number(r[ix.CurrentIndex]||0),questionOrderJson:String(d[i+1][ix.QuestionOrderJSON]||'[]'),choiceOrderJson:String(d[i+1][ix.ChoiceOrderJSON]||'{}'),answersJson:String(d[i+1][ix.AnswersJSON]||'{}'),tabSwitchCount:Number(r[ix.TabSwitchCount]||0)}));}
function sessionById_(id){return sessions_().find(s=>s.sessionId===String(id||''))||null;}function activeSessionByStudent_(id){return sessions_().find(s=>s.studentId===String(id||'')&&s.status==='ACTIVE')||null;}function requireActive_(id){const s=sessionById_(id);if(!s)throw new Error('ไม่พบเซสชันสอบ');if(s.status!=='ACTIVE')throw new Error('ข้อสอบถูกส่งแล้ว');return s;}
function questionPayload_(s){const ord=parse_(s.questionOrderJson,[]),i=num_(s.currentIndex,0);if(i>=ord.length)return null;const q=questions_().find(x=>x.qid===ord[i]);if(!q)throw new Error('ไม่พบข้อสอบ '+ord[i]);const cm=parse_(s.choiceOrderJson,{}),p=cm[q.qid]||[0,1,2,3];return{qid:q.qid,number:i+1,total:ord.length,text:q.question,choices:p.map(n=>q.choices[n])};}
function sessionPayload_(s,settings,resumed){const first=parse_(s.questionOrderJson,[])[0],q=questions_().find(x=>x.qid===first);return{sessionId:s.sessionId,student:{studentId:s.studentId,fullName:s.fullName,className:s.className},examSet:q?q.group:'',expiresAtMs:s.expiresAt.getTime(),maxTabSwitch:num_(settings.MAX_TAB_SWITCH,3),tabSwitchCount:num_(s.tabSwitchCount,0),resumed:!!resumed,question:questionPayload_(s)};}
function append_(name,obj){const sh=sheet_(name),h=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],last=h.reduce((a,x,i)=>x?i:a,-1);sh.appendRow(h.slice(0,last+1).map(x=>Object.prototype.hasOwnProperty.call(obj,x)?obj[x]:''));}
function updateSession_(row,f){const sh=sheet_(SH.SESSIONS),h=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0];Object.keys(f).forEach(k=>{const c=h.indexOf(k);if(c>=0)sh.getRange(row,c+1).setValue(f[k]);});}
function audit_(sid,id,e,details){append_(SH.AUDIT,{Timestamp:new Date(),SessionID:String(sid||''),StudentID:String(id||''),Event:String(e||''),Details:String(details||'')});}
function existingResult_(sid){const r=objects_(sheet_(SH.RESPONSES)).find(x=>String(x.SessionID||'')===String(sid||''));if(!r)return{submitted:true,message:'ข้อสอบถูกส่งแล้ว'};const show=bool_(settings_().SHOW_SCORE);return{submitted:true,message:'ระบบได้รับคำตอบเรียบร้อยแล้ว',score:show?Number(r.Score||0):null,maxScore:show?Number(r.MaxScore||0):null,percent:show?Number(r.Percent||0):null,reason:String(r.Reason||'')};}
function deleteByStudent_(name,id){const sh=sheet_(name),d=sh.getDataRange().getDisplayValues(),c=d[0].indexOf('StudentID');if(c<0)return;for(let r=d.length-1;r>=1;r--)if(String(d[r][c]).trim()===String(id).trim())sh.deleteRow(r+1);}
function examCode_(c,s){if(String(c||'').trim()!==String(s.EXAM_CODE||'').trim())throw new Error('รหัสเข้าห้องสอบไม่ถูกต้อง');}function admin_(p,s){if(String(p||'').trim()!==String(s.ADMIN_PIN||'').trim())throw new Error('PIN ผู้ดูแลไม่ถูกต้อง');}
function allowedClass_(c,s){const a=String(s.ALLOWED_CLASSES||'').split(',').map(norm_).filter(Boolean);return!a.length||a.indexOf(norm_(c))>=0;}function norm_(s){return String(s||'').toLowerCase().replace(/\s/g,'').replace(/^ม\./,'').replace(/^m\./,'');}
function window_(s){const now=new Date();if(s.START_TIME){const x=new Date(s.START_TIME);if(!isNaN(x)&&now<x)throw new Error('ยังไม่ถึงเวลาเปิดข้อสอบ');}if(s.END_TIME){const x=new Date(s.END_TIME);if(!isNaN(x)&&now>x)throw new Error('หมดเวลาเข้าสอบแล้ว');}}
function lock_(fn){const l=LockService.getScriptLock();l.waitLock(15000);try{return fn();}finally{l.releaseLock();}}function shuffle_(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1)),t=a[i];a[i]=a[j];a[j]=t;}return a;}function parse_(s,f){try{return JSON.parse(String(s||''));}catch(e){return f;}}function bool_(v){return String(v||'').trim().toUpperCase()==='TRUE';}function num_(v,f){const n=Number(v);return isFinite(n)?n:f;}function fmt_(v){const d=new Date(v);return isNaN(d)?String(v||''):Utilities.formatDate(d,TZ,'yyyy-MM-dd HH:mm:ss');}function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
